#ifndef PECHKA_LIGHTING_H
#define PECHKA_LIGHTING_H

static const char *LIGHT_VS =
    "#version 330\n"
    "in vec3 vertexPosition;\n"
    "in vec3 vertexNormal;\n"
    "in vec2 vertexTexCoord;\n"
    "in vec4 vertexColor;\n"
    "uniform mat4 mvp;\n"
    "uniform mat4 matModel;\n"
    "uniform mat4 matNormal;\n"
    "out vec3 fragPos;\n"
    "out vec3 fragNormal;\n"
    "out vec2 fragTexCoord;\n"
    "out vec4 fragColor;\n"
    "void main(){\n"
    "  vec4 world = matModel * vec4(vertexPosition, 1.0);\n"
    "  fragPos = world.xyz;\n"
    "  fragNormal = normalize(mat3(matNormal) * vertexNormal);\n"
    "  fragTexCoord = vertexTexCoord;\n"
    "  fragColor = vertexColor;\n"
    "  gl_Position = mvp * vec4(vertexPosition, 1.0);\n"
    "}\n";

static const char *LIGHT_FS =
    "#version 330\n"
    "in vec3 fragPos;\n"
    "in vec3 fragNormal;\n"
    "in vec2 fragTexCoord;\n"
    "in vec4 fragColor;\n"
    "uniform sampler2D texture0;\n"
    "uniform vec4 colDiffuse;\n"
    "uniform vec3 viewPos;\n"
    "uniform vec3 sunDir;\n"
    "uniform vec3 sunColor;\n"
    "uniform vec3 firePos;\n"
    "uniform float firePower;\n"
    "out vec4 finalColor;\n"
    "void main(){\n"
    "  vec3 n = normalize(fragNormal);\n"
    "  vec3 albedo = texture(texture0, fragTexCoord).rgb * colDiffuse.rgb * fragColor.rgb;\n"
    "  vec3 L = normalize(-sunDir);\n"
    "  float ndl = clamp(dot(n, L), 0.0, 1.0);\n"
    "  float hemi = n.y * 0.35 + 0.65;\n"
    "  vec3 ambient = vec3(0.38, 0.36, 0.32) * hemi;\n"
    "  vec3 lit = albedo * (ambient + sunColor * ndl * 0.85);\n"
    "  vec3 V = normalize(viewPos - fragPos);\n"
    "  vec3 H = normalize(L + V);\n"
    "  lit += sunColor * pow(max(dot(n, H), 0.0), 40.0) * 0.16;\n"
    "  vec3 toF = firePos - fragPos;\n"
    "  float fd = length(toF);\n"
    "  float fatt = firePower / (1.0 + fd * fd * 0.45);\n"
    "  lit += albedo * vec3(1.0, 0.45, 0.12) * max(dot(n, normalize(toF + vec3(0.001))), 0.0) * fatt;\n"
    "  float fog = smoothstep(14.0, 36.0, length(viewPos - fragPos));\n"
    "  lit = mix(lit, vec3(0.62, 0.72, 0.82), fog * 0.35);\n"
    "  finalColor = vec4(lit, 1.0);\n"
    "}\n";

#endif
